spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pos_db
    username: pos_user
    password: pos_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
